name: autoProfile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  autoProfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Profile File
        run: |
          ls
          curl -o Outbound.conf https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Outbound.conf
